# Generated by Django 3.2 on 2023-07-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
