# Generated by Django 3.2 on 2023-07-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_auto_20230710_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
