# Generated by Django 3.2 on 2023-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_delete_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
