# Generated by Django 3.2 on 2023-07-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
